---
title: "Appendix 1"
output:
  word_document: default
  pdf_document: default
always_allow_html: yes
---

```{r setup, include=FALSE} 
knitr::opts_chunk$set(warning = FALSE, message = FALSE) 
```

```{r}
library(readxl)
library(tidyverse)
library(corrplot)
library(dplyr)
library(ggpubr)
library(reshape2)
library(ggmap)
library(maps)
library(mapdata)
library(fuzzyjoin)
library(carData)
library(scales)
library(ggthemes)
library(dplyr)
library(lubridate)
library(zoo)
library(fpp2)
library(ggfortify)
library(leaflet)
library(sp)
library(readr)
library(reactable)
library(janitor)
library(effects)
```

```{r}
data('MplsStops', package='carData')
df = MplsStops
```

```{r}
df$policePrecinct = as.factor(df$policePrecinct)
#df$date = as_datetime(df$date)
str(df)
```
```{r fig.width=12}
summary = data.frame(unclass(summary(df)),
                     check.names = TRUE)
row.names(summary) = NULL
summary = janitor::clean_names(summary)
colnames(summary) = gsub('x_','',colnames(summary))
```

```{r}
#Factoral Data Exploration

problemplot = df %>%
  group_by(problem) %>%
  summarise(count = n()) %>%
  ggplot(aes(x = reorder(problem,(-count)), y = count, label = count)) +
  geom_bar(stat = 'identity', fill = 'lightblue') +
  geom_text(size = 8, position = position_dodge(width = 3),
            vjust = 3) +
  xlab('') +
  ylab('') +
  ggtitle('Reasons for Traffic Stop') +
  theme(axis.text.x = element_text(size = 20))

citationplot = df %>%
  group_by(citationIssued) %>%
  summarise(count = n()) %>%
  ggplot(aes(x = reorder(citationIssued,(-count)), y = count, label = count)) +
  geom_bar(stat = 'identity', fill = 'lightblue') +
    geom_text(size = 8, position = position_dodge(width = 3),
            vjust = .4) +
  xlab('') +
  ylab('') +
  ggtitle('Citation Issued') +
  theme(axis.text.x = element_text(size = 20))

personplot = df %>%
  group_by(personSearch) %>%
  summarise(count = n()) %>%
  ggplot(aes(x = reorder(personSearch,(-count)), y = count, label = count)) +
  geom_bar(stat = 'identity', fill = 'lightblue') +
  geom_text(size = 8, position = position_dodge(width = 3),
            vjust = .4) +
  xlab('') +
  ylab('') +
  ggtitle('Person Searched') +
  theme(axis.text.x = element_text(size = 20))

vehicleplot = df %>%
  group_by(vehicleSearch) %>%
  summarise(count = n()) %>%
  ggplot(aes(x = reorder(vehicleSearch,(-count)), y = count, label = count)) +
  geom_bar(stat = 'identity', fill = 'lightblue') +
  geom_text(size = 8, position = position_dodge(width = 3),
            vjust = .3) +
  xlab('') +
  ylab('') +
  ggtitle('Vehicle Searched') +
  theme(axis.text.x = element_text(size = 20))

preraceplot = df %>%
  group_by(preRace) %>%
  summarise(count = n()) %>%
  ggplot(aes(x = reorder(preRace,(-count)), y = count, label = count)) +
  geom_bar(stat = 'identity', fill = 'lightblue') +
  geom_text(size = 8, position = position_dodge(width = 3),
            vjust = .3) +
  xlab('') +
  ylab('') +
  ggtitle('Pre-Race of Driver') +
  theme(axis.text.x = element_text(size = 12))

raceplot = df %>%
  group_by(race) %>%
  summarise(count = n()) %>%
  ggplot(aes(x = reorder(race,(-count)), y = count, label = count)) +
  geom_bar(stat = 'identity', fill = 'lightblue') +
  geom_text(size = 8, position = position_dodge(width = 3),
            vjust = .3) +
  xlab('') +
  ylab('') +
  ggtitle('Race of Driver') +
  theme(axis.text.x = element_text(size = 12))

genderplot = df %>%
  group_by(gender) %>%
  summarise(count = n()) %>%
  ggplot(aes(x = reorder(gender,(-count)), y = count, label = count)) +
  geom_bar(stat = 'identity', fill = 'lightblue') +
  geom_text(size = 8, position = position_dodge(width = 3),
            vjust = .7) +
  xlab('') +
  ylab('') +
  ggtitle('Gender of Driver') +
  theme(axis.text.x = element_text(size = 20))

precinctplot = df %>%
  group_by(policePrecinct) %>%
  summarise(count = n()) %>%
  ggplot(aes(x = reorder(policePrecinct,(-count)), y = count, label = count)) +
  geom_bar(stat = 'identity', fill = 'lightblue') +
  geom_text(size = 8, position = position_dodge(width = 3),
            vjust = 3) +
  xlab('') +
  ylab('') +
  ggtitle('Police Precinct') +
  theme(axis.text.x = element_text(size = 20))
```

```{r fig.width= 11}
problemplot
citationplot
personplot
vehicleplot
preraceplot
raceplot
genderplot
precinctplot
```

```{r}
prop.test(x = c(26098, 25822), n = c(51920, 51920))
```

```{r fig.width = 15}

 black = df %>%
  filter(race == 'Black') %>%
  group_by(citationIssued) %>%
  summarise(count = n()) %>%
  ggplot(aes(x = reorder(citationIssued,(-count)), y = count, label = count)) +
  geom_bar(stat = 'identity', fill = 'lightblue') +
    geom_text(size = 8, position = position_dodge(width = 3),
            vjust = 1) +
  xlab('') +
  ylab('') +
  ggtitle('Citation Issued: Black') +
  theme(axis.text.x = element_text(size = 20))

white = df %>%
  filter(race == 'White') %>%
  group_by(citationIssued) %>%
  summarise(count = n()) %>%
  ggplot(aes(x = reorder(citationIssued,(-count)), y = count, label = count)) +
  geom_bar(stat = 'identity', fill = 'lightblue') +
    geom_text(size = 8, position = position_dodge(width = 3),
            vjust = 1) +
  xlab('') +
  ylab('') +
  ggtitle('Citation Issued: White') +
  theme(axis.text.x = element_text(size = 20))

unknown = df %>%
  filter(race == 'Unknown') %>%
  group_by(citationIssued) %>%
  summarise(count = n()) %>%
  ggplot(aes(x = reorder(citationIssued,(-count)), y = count, label = count)) +
  geom_bar(stat = 'identity', fill = 'lightblue') +
    geom_text(size = 8, position = position_dodge(width = 3),
            vjust = .6) +
  xlab('') +
  ylab('') +
  ggtitle('Citation Issued: Unknown Race') +
  theme(axis.text.x = element_text(size = 20))

east = df %>%
  filter(race == 'East African') %>%
  group_by(citationIssued) %>%
  summarise(count = n()) %>%
  ggplot(aes(x = reorder(citationIssued,(-count)), y = count, label = count)) +
  geom_bar(stat = 'identity', fill = 'lightblue') +
    geom_text(size = 8, position = position_dodge(width = 3),
            vjust = 1) +
  xlab('') +
  ylab('') +
  ggtitle('Citation Issued: East African') +
  theme(axis.text.x = element_text(size = 20))

latino = df %>%
  filter(race == 'Latino') %>%
  group_by(citationIssued) %>%
  summarise(count = n()) %>%
  ggplot(aes(x = reorder(citationIssued,(-count)), y = count, label = count)) +
  geom_bar(stat = 'identity', fill = 'lightblue') +
    geom_text(size = 8, position = position_dodge(width = 3),
            vjust = 1) +
  xlab('') +
  ylab('') +
  ggtitle('Citation Issued: Latino') +
  theme(axis.text.x = element_text(size = 20))

native = df %>%
  filter(race == 'Native American') %>%
  group_by(citationIssued) %>%
  summarise(count = n()) %>%
  ggplot(aes(x = reorder(citationIssued,(-count)), y = count, label = count)) +
  geom_bar(stat = 'identity', fill = 'lightblue') +
    geom_text(size = 8, position = position_dodge(width = 3),
            vjust = 1) +
  xlab('') +
  ylab('') +
  ggtitle('Citation Issued: Native Amer') +
  theme(axis.text.x = element_text(size = 20))

other = df %>%
  filter(race == 'Other') %>%
  group_by(citationIssued) %>%
  summarise(count = n()) %>%
  ggplot(aes(x = reorder(citationIssued,(-count)), y = count, label = count)) +
  geom_bar(stat = 'identity', fill = 'lightblue') +
    geom_text(size = 8, position = position_dodge(width = 3),
            vjust = 1) +
  xlab('') +
  ylab('') +
  ggtitle('Citation Issued: Other') +
  theme(axis.text.x = element_text(size = 20))

asian = df %>%
  filter(race == 'Asian') %>%
  group_by(citationIssued) %>%
  summarise(count = n()) %>%
  ggplot(aes(x = reorder(citationIssued,(-count)), y = count, label = count)) +
  geom_bar(stat = 'identity', fill = 'lightblue') +
    geom_text(size = 8, position = position_dodge(width = 3),
            vjust = 1) +
  xlab('') +
  ylab('') +
  ggtitle('Citation Issued: Asian') +
  theme(axis.text.x = element_text(size = 20))

ggarrange(black, white, native,  ncol = 3, nrow = 1)
```
```{r}
prop.test(x = c(1505, 919), n = c(6685, 4711))
prop.test(x = c(86, 919), n = c(690, 4711))
```

```{r}
prop.test(x = c(8535, 6992), n = c(15220, 11703))
prop.test(x = c(826, 6992), n = c(1516, 11703))
```

```{r}
attach(df)
 chi2 = chisq.test(df$citationIssued, df$race)
 chi2
 corrplot(chi2$stdres, is.cor = FALSE)
```

```{r fig.width=15}

 black = df %>%
  filter(race == 'Black') %>%
  group_by(personSearch) %>%
  summarise(count = n()) %>%
  ggplot(aes(x = reorder(personSearch,(-count)), y = count, label = count)) +
  geom_bar(stat = 'identity', fill = 'lightblue') +
    geom_text(size = 8, position = position_dodge(width = 3),
            vjust = 1) +
  xlab('') +
  ylab('') +
  ggtitle('Person Searched: Black') +
  theme(axis.text.x = element_text(size = 20))

white = df %>%
  filter(race == 'White') %>%
  group_by(personSearch) %>%
  summarise(count = n()) %>%
  ggplot(aes(x = reorder(personSearch,(-count)), y = count, label = count)) +
  geom_bar(stat = 'identity', fill = 'lightblue') +
    geom_text(size = 8, position = position_dodge(width = 3),
            vjust = 1) +
  xlab('') +
  ylab('') +
  ggtitle('Person Searched: White') +
  theme(axis.text.x = element_text(size = 20))

native = df %>%
  filter(race == 'Native American') %>%
  group_by(personSearch) %>%
  summarise(count = n()) %>%
  ggplot(aes(x = reorder(personSearch,(-count)), y = count, label = count)) +
  geom_bar(stat = 'identity', fill = 'lightblue') +
    geom_text(size = 8, position = position_dodge(width = 3),
            vjust = 1) +
  xlab('') +
  ylab('') +
  ggtitle('Person Searched: Native Amer') +
  theme(axis.text.x = element_text(size = 20))

ggarrange(black, white, native,  ncol = 3, nrow = 1)
```

```{r}
prop.test(x = c(464, 3099), n = c(1052, 15220))
prop.test(x = c(3099, 954), n = c(15220, 11703))
```

```{r}
nativeinspect = df%>%filter(race == 'Native American')

colorFactor_search = colorFactor(
  palette = c('blue', 'darkorange'),
  levels = c('NO','YES'))

leaflet(sample_n(nativeinspect, 300)) %>%
  addProviderTiles(provider = 'Stamen') %>%
  addCircles(
    color = ~colorFactor_search(nativeinspect$personSearch),
    opacity = 1,
    fillOpacity = 1
  ) %>%
  addLegend(
    pal = colorFactor_search,
    values = c('NO', 'YES'),
    title = 'Search: Native American',
    position = 'topleft',
    opacity=1
  )
```

```{r fig.width=15}
pp1 = df %>%
  filter(race == 'Native American',
         policePrecinct == '1') %>%
  group_by(personSearch) %>%
  summarise(count = n()) %>%
  ggplot(aes(x = reorder(personSearch,(-count)), y = count, label = count)) +
  geom_bar(stat = 'identity', fill = 'lightblue') +
    geom_text(size = 8, position = position_dodge(width = 3),
            vjust = 1) +
  xlab('') +
  ylab('') +
  ggtitle('Precinct 1') +
  theme(axis.text.x = element_text(size = 20))

 pp2 = df %>%
  filter(race == 'Native American',
         policePrecinct == '2') %>%
  group_by(personSearch) %>%
  summarise(count = n()) %>%
  ggplot(aes(x = reorder(personSearch,(-count)), y = count, label = count)) +
  geom_bar(stat = 'identity', fill = 'lightblue') +
    geom_text(size = 8, position = position_dodge(width = 3),
            vjust = 1) +
  xlab('') +
  ylab('') +
  ggtitle('Precinct 2') +
  theme(axis.text.x = element_text(size = 20))

 pp3 = df %>%
  filter(race == 'Native American',
         policePrecinct == '3') %>%
  group_by(personSearch) %>%
  summarise(count = n()) %>%
  ggplot(aes(x = reorder(personSearch,(-count)), y = count, label = count)) +
  geom_bar(stat = 'identity', fill = 'lightblue') +
    geom_text(size = 8, position = position_dodge(width = 3),
            vjust = 1) +
  xlab('') +
  ylab('') +
  ggtitle('Precinct 3') +
  theme(axis.text.x = element_text(size = 20))
 
  pp4 = df %>%
  filter(race == 'Native American',
         policePrecinct == '4') %>%
  group_by(personSearch) %>%
  summarise(count = n()) %>%
  ggplot(aes(x = reorder(personSearch,(-count)), y = count, label = count)) +
  geom_bar(stat = 'identity', fill = 'lightblue') +
    geom_text(size = 8, position = position_dodge(width = 3),
            vjust = 1) +
  xlab('') +
  ylab('') +
  ggtitle('Precinct 4') +
  theme(axis.text.x = element_text(size = 20))
  
   pp5 = df %>%
  filter(race == 'Native American',
         policePrecinct == '5') %>%
  group_by(personSearch) %>%
  summarise(count = n()) %>%
  ggplot(aes(x = reorder(personSearch,(-count)), y = count, label = count)) +
  geom_bar(stat = 'identity', fill = 'lightblue') +
    geom_text(size = 8, position = position_dodge(width = 3),
            vjust = 1) +
  xlab('') +
  ylab('') +
  ggtitle('Precinct 5') +
  theme(axis.text.x = element_text(size = 20))

ggarrange(pp1, pp2, pp3, pp4, pp5, ncol = 5, nrow = 1)
```

```{r fig.width=15}
pp1 = df %>%
  filter(race == 'Native American',
         policePrecinct == '3') %>%
  group_by(personSearch) %>%
  summarise(count = n()) %>%
  ggplot(aes(x = reorder(personSearch,(-count)), y = count, label = count)) +
  geom_bar(stat = 'identity', fill = 'lightblue') +
    geom_text(size = 8, position = position_dodge(width = 3),
            vjust = 1) +
  xlab('') +
  ylab('') +
  ggtitle('Precinct 3') +
  theme(axis.text.x = element_text(size = 20))

ppAll = df %>%
  filter(race == 'Native American',
         policePrecinct != '3') %>%
  group_by(personSearch) %>%
  summarise(count = n()) %>%
  ggplot(aes(x = reorder(personSearch,(-count)), y = count, label = count)) +
  geom_bar(stat = 'identity', fill = 'lightblue') +
    geom_text(size = 8, position = position_dodge(width = 3),
            vjust = 1) +
  xlab('') +
  ylab('') +
  ggtitle('Precincts 1, 2, 4, 5') +
  theme(axis.text.x = element_text(size = 20))

ggarrange(pp1, ppAll, ncol = 2, nrow = 1)
```

```{r}
prop.test(x = c(283, 181), n = c(750, 766))
prop.test(x = c(181, 3099), n = c(766, 15220))
```
```{r fig.height=6}
attach(df%>%
         filter(race == 'Native American',
                policePrecinct == '3'))
chi1 = chisq.test(personSearch, neighborhood)
chi1
corrplot(chi1$stdres, is.cor = FALSE)
```

```{r}
df %>%
  group_by(hour = hour(date), personSearch) %>%
  summarize(count = length(date)) %>%
  ggplot(aes(x=hour, y=count, fill = personSearch)) +
  geom_bar(stat='identity') +
  ylab('Total Traffic Stops') +
  ggtitle('Total Traffic Stops by Time of Day')
```

```{r fig.height=8}
df1 = df %>% mutate(hour = format(df$date, '%H'))
df1$hour = as.factor(df1$hour)
attach(df1)
chi3 = chisq.test(personSearch, hour)
chi3
corrplot(chi3$stdres, is.cor = FALSE)
```

```{r fig.height=8}
chi4 = chisq.test(citationIssued, hour)
chi4
corrplot(chi4$stdres, is.cor = FALSE)
```

```{r}
mytab = with(df1,table(race, hour))
chi5 = chisq.test(mytab)
chi5
corrplot(chi5$stdres, is.cor = FALSE)
```

```{r fig.width=8}
byday = df %>%
  group_by(date=floor_date(date, '1 day')) %>%
  summarise(count = length(date))
  
byday %>%  
  ggplot(aes(x=date, y=count)) +
  geom_line() 

byday = byday %>%
  dplyr::mutate(weeklyavg = zoo::rollmean(count, k=7, fill=NA))
```

```{r fig.width=12, fig.height=7}
byday %>%
  pivot_longer(names_to = 'rolling_mean_key',
                      values_to = 'rolling_mean_value',
                      cols = c(weeklyavg,
                      count)) %>%
  ggplot(aes(x=date,
                      y=rolling_mean_value,
                      color = rolling_mean_key)) +
  geom_line() +
  labs(title='Weekly Rolling Average of Traffic Stops',
                y='Traffic Stops',
                x='Date',
                color='Metric',) +
  scale_x_datetime(breaks=date_breaks('1 month'), date_labels = '%m %Y')
 # hrbrthemes::theme_ipsum_rc()
```

```{r}
bydayts = ts(byday$count)
plot(diff(log(bydayts)))
ggAcf(bydayts)
```

```{r}
library(tidymodels)
set.seed(421)
split = initial_split(data = df, prop = 0.8, strata = citationIssued)
train = split %>%
  training()
test = split %>%
  testing()
```

```{r}
df1 = na.omit(df)
model1 = glm(citationIssued ~ problem + personSearch + vehicleSearch + preRace + race + gender + policePrecinct, df1, family='binomial')
summary(model1)
```

```{r}
library(car)
vif(model1)
```

```{r}
model2 = update(model1,~. -vehicleSearch)
anova(model2,model1,test='Chi')
```

```{r}
model3 = update(model2,~. + neighborhood)
anova(model3,model2,test='Chi')
```

```{r}
model4 = update(model3,~. + race*gender)
anova(model4,model3,test='Chi')
```

```{r}
test$yhat = predict(model2, test, type='response')

prediction = rep(0, dim(test)[1])
prediction[test$yhat > .5] = 1
test$citationIssued = gsub('yes','1',test$citationIssued)
test$citationIssued = gsub('no','0',test$citationIssued)
table(prediction, test$citationIssued)
#mean(prediction == test$y)
```

```{r}
test$yhat = predict(model3, test, type='response')

prediction = rep(0, dim(test)[1])
prediction[test$yhat > .5] = 1
test$citationIssued = gsub('yes','1',test$citationIssued)
test$citationIssued = gsub('no','0',test$citationIssued)
table(prediction, test$citationIssued)
#mean(prediction == test$y)
```

```{r}
test$yhat = predict(model4, test, type='response')

prediction = rep(0, dim(test)[1])
prediction[test$yhat > .5] = 1
test$citationIssued = gsub('yes','1',test$citationIssued)
test$citationIssued = gsub('no','0',test$citationIssued)
table(prediction, test$citationIssued)
#mean(prediction == test$y)
```

```{r}
model5 = update(model4,~. + race*problem)
anova(model5,model4,test='Chi')
```

```{r}
test$yhat = predict(model5, test, type='response')

prediction = rep(0, dim(test)[1])
prediction[test$yhat > .5] = 1
test$citationIssued = gsub('yes','1',test$citationIssued)
test$citationIssued = gsub('no','0',test$citationIssued)
table(prediction, test$citationIssued)
#mean(prediction == test$y)
```

```{r}
model6 = update(model5,~. + gender*policePrecinct)
anova(model6,model5,test='Chi')
```

```{r}
model6
```

```{r fig.height = 12, fig.width=25}
plot(allEffects(model2))
```

```{r}
test$yhat = predict(model6, test, type='response')

prediction = rep(0, dim(test)[1])
prediction[test$yhat > .5] = 1
test$citationIssued = gsub('yes','1',test$citationIssued)
test$citationIssued = gsub('no','0',test$citationIssued)
table(prediction, test$citationIssued)
#mean(prediction == test$y)
```

```{r}
model7 = update(model6,~. + gender*problem)
anova(model7,model6,test='Chi')
```

```{r}
test$yhat = predict(model7, test, type='response')

prediction = rep(0, dim(test)[1])
prediction[test$yhat > .5] = 1
test$citationIssued = gsub('yes','1',test$citationIssued)
test$citationIssued = gsub('no','0',test$citationIssued)
table(prediction, test$citationIssued)
#mean(prediction == test$y)
```

